url: https://y7kim.github.io
baseurl: /agency-jekyll-theme

# Site settings
title: Elliott Cunningham
email: me@elliottcunningham.com
description: "London based Data Consultant"

# Postal address (add as many lines as necessary)
address:
  - line: Walthamstow, London

# Build settings
markdown: kramdown
permalink: pretty